# Generated by Django 5.0.6 on 2024-05-25 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('area_de_atuacao', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
