# Generated by Django 5.0.6 on 2024-05-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='telefone',
            field=models.IntegerField(max_length=20),
        ),
    ]
