# Generated by Django 5.0.6 on 2024-06-01 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitys', '0001_initial'),
        ('infos', '0003_info_created_at_info_deleted_at_info_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='visualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='info',
            name='area_de_atuacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='activitys.activity'),
        ),
    ]
